name: Check Gov Notifications

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 10:00 UTC every day (6:00 AM ET)
  workflow_dispatch:

jobs:
  run-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: yarn install 

      - name: Run the governance notifier script
        run: npx ts-node scripts/governance-notifier.ts
        env:
          MAINNET_RPC: http://realms-realms-c335.mainnet.rpcpool.com/258d3727-bb96-409d-abea-0b1b4c48af29/
          CLUSTER_URL: http://realms-realms-c335.mainnet.rpcpool.com/258d3727-bb96-409d-abea-0b1b4c48af29/
          WEBHOOK_URL: https://webhook.site/b48b863e-d364-433a-b55b-bbc86db7d1ed